version: '3.7'

services:

  access_directory_flask:
    build:
      context: ./services/access_directory_flask
      dockerfile: Dockerfile
    expose:
      - 5000
    volumes:
      # Specify an absolute path mapping
      - /mnt/public1:/mnt/public1

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - access_directory_flask

